In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/pd_speech_features.csv')
df

id  gender      PPE      DFA     RPDE  numPulses  numPeriodsPulses  \
0    142       1  0.28937  0.71427  0.40286        426               424   
1    142       1  0.29855  0.70809  0.47168        441               439   
2     77       0  0.63101  0.82411  0.80353        292               288   
3    156       1  0.27100  0.63303  0.66652        305               304   
4    202       0  0.83786  0.73017  0.70689         82                74   
..   ...     ...      ...      ...      ...        ...               ...   
751    0       1  0.85083  0.67604  0.58982        232               231   
752  251       0  0.88389  0.72335  0.46815        381               380   
753    5       1  0.82016  0.63124  0.37031        266               265   
754  138       1  0.82570  0.73685  0.32865        344               343   
755   25       0  0.83865  0.76831  0.34722        345               344   

     meanPeriodPulses  stdDevPeriodPulses  locPctJitter  ...  \
0            0.003429            0.000089       0.00131  ...   
1            0.003445            0.000145       0.00190  ...   
2            0.006561            0.002738       0.01505  ...   
3            0.006317            0.000028       0.00059  ...   
4            0.006768            0.001837       0.01119  ...   
..                ...                 ...           ...  ...   
751          0.008340            0.000060       0.00176  ...   
752          0.005069            0.000103       0.00076  ...   
753          0.007257            0.000049       0.00086  ...   
754          0.005610            0.000059       0.00111  ...   
755          0.005599            0.000053       0.00082  ...   

     tqwt_kurtosisValue_dec_28  tqwt_kurtosisValue_dec_29  \
0                     133.0527                    88.5570   
1                      54.3108                    49.3134   
2                       4.7398                     5.3789   
3                       3.2374                     4.2239   
4                       5.8171                     5.8815   
..                         ...                        ...   
751                     1.5643                     2.3308   
752                    51.5607                    44.4641   
753                     1.7350                    16.2074   
754                    62.6654                    16.0953   
755                    26.1771                    13.3119   

     tqwt_kurtosisValue_dec_30  tqwt_kurtosisValue_dec_31  \
0                      60.3057                    58.4251   
1                      28.0899                    21.5006   
2                       4.0231                     4.0372   
3                       4.4016                     3.0632   
4                       4.1913                     4.0224   
..                         ...                        ...   
751                     9.4959                    10.7458   
752                    26.1586                     6.3076   
753                    27.8125                    48.7381   
754                     4.3213                     2.7925   
755                    10.7551                    11.3129   

     tqwt_kurtosisValue_dec_32  tqwt_kurtosisValue_dec_33  \
0                      67.8869                    45.8100   
1                      34.4451                    31.7497   
2                       2.6949                     2.6998   
3                       1.8349                     1.6287   
4                       3.1601                     2.7833   
..                         ...                        ...   
751                    11.0177                     4.8066   
752                     2.8601                     2.5361   
753                    69.1536                    65.6525   
754                     3.1611                     3.9128   
755                    10.2577                    11.5123   

     tqwt_kurtosisValue_dec_34  tqwt_kurtosisValue_dec_35  \
0                      41.7047                    46.0282   
1  

In [3]:
key_words = ['mfcc', 'tqwt', 'delta', 'det_entropy', 'vfer', 'gq', 'gne', 'imf_nsr', 'imf_snr',
            'ed', 'tkeo', 'log_energy', 'app_entropy', 'det_lt_entropy', 'app_lt_entropy']

unnecessary_cols = [col for key in key_words for col in df.columns if key in col.lower()]

# print("Unnecessary columns:", unnecessary_cols)

df_features = df.drop(columns=['f1', 'f2', 'f3', 'f4', 'b1', 'b2', 'b3', 'b4', 
                              'minIntensity', 'maxIntensity', 'meanIntensity', 'Ea', 'Ea2',
                              'locDbShimmer', 'numPulses', 'numPeriodsPulses', 'DFA'] 
                              + unnecessary_cols)
df_features

id  gender      PPE     RPDE  meanPeriodPulses  stdDevPeriodPulses  \
0    142       1  0.28937  0.40286          0.003429            0.000089   
1    142       1  0.29855  0.47168          0.003445            0.000145   
2     77       0  0.63101  0.80353          0.006561            0.002738   
3    156       1  0.27100  0.66652          0.006317            0.000028   
4    202       0  0.83786  0.70689          0.006768            0.001837   
..   ...     ...      ...      ...               ...                 ...   
751    0       1  0.85083  0.58982          0.008340            0.000060   
752  251       0  0.88389  0.46815          0.005069            0.000103   
753    5       1  0.82016  0.37031          0.007257            0.000049   
754  138       1  0.82570  0.32865          0.005610            0.000059   
755   25       0  0.83865  0.34722          0.005599            0.000053   

     locPctJitter  locAbsJitter  rapJitter  ppq5Jitter  ddpJitter  locShimmer  \
0         0.00131      0.000004    0.00013     0.00037    0.00040     0.04988   
1         0.00190      0.000007    0.00021     0.00056    0.00062     0.05372   
2         0.01505      0.000099    0.00442     0.00875    0.01327     0.13841   
3         0.00059      0.000004    0.00014     0.00032    0.00041     0.17188   
4         0.01119      0.000076    0.00341     0.00656    0.01022     0.18701   
..            ...           ...        ...         ...        ...         ...   
751       0.00176      0.000015    0.00057     0.00111    0.00171     0.09902   
752       0.00076      0.000004    0.00011     0.00030    0.00034     0.02978   
753       0.00086      0.000006    0.00020     0.00045    0.00059     0.02734   
754       0.00111      0.000006    0.00021     0.00052    0.00062     0.01803   
755       0.00082      0.000005    0.00016     0.00036    0.00047     0.04631   

     apq3Shimmer  apq5Shimmer  apq11Shimmer  ddaShimmer  \
0        0.02501      0.02894       0.04355     0.07503   
1        0.02610      0.03099       0.04773     0.07829   
2        0.06392      0.08508       0.11153     0.19176   
3        0.09051      0.12890       0.12624     0.27152   
4        0.10070      0.15668       0.26624     0.30209   
..           ...          ...           ...         ...   
751      0.05094      0.06497       0.07772     0.15282   
752      0.01597      0.01916       0.02271     0.04790   
753      0.01309      0.01662       0.02548     0.03926   
754      0.00950      0.01146       0.01501     0.02849   
755      0.02463      0.03177       0.03394     0.07389   

     meanAutoCorrHarmonicity  meanNoiseToHarmHarmonicity  \
0                   0.986148                    0.014834   
1                   0.970784                    0.037006   
2                   0.823307                    0.278253   
3                   0.793984                    0.277690   
4                   0.590345                    0.737512   
..                       ...                         ...   
751                 0.974846                    0.026313   
752                 0.995544                    0.004480   
753                 0.996592                    0.003428   
754                 0.993155                    0.006899   
755                 0.990257                    0.009861   

     meanHarmToNoiseHarmonicity  class  
0                        20.384      1  
1                        20.079      1  
2                         9.149      1  
3                         6.280      0  
4                         1.655      1  
..                          ...    ...  
751                      17.651      1  
752                      24.005      0  
753                      26.686      1  
754                      21.949      1  
755                      20.474      1  

[756 rows x 20 columns]

In [4]:
df_features.to_csv('../data/pd_speech_features_processed.csv', index=False)

In [5]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import joblib

In [6]:
df = pd.read_csv('../data/pd_speech_features_processed.csv')

id_col = df['id'] if 'id' in df.columns else None
class_col = df['class'] if 'class' in df.columns else None

features = df.drop(columns=['id', 'class'], errors='ignore')


scaler = MinMaxScaler(clip=True)
features_scaled = scaler.fit_transform(features)

print(features_scaled)

df_scaled = pd.DataFrame(features_scaled, columns=features.columns)
if id_col is not None:
    df_scaled.insert(0, 'id', id_col)

if class_col is not None:
    df_scaled['class'] = class_col

df_scaled.to_csv('../data/pd_speech_features_scaled.csv', index=False)

joblib.dump(scaler, "../data/scaler/scaler.pkl")

features


[[1.         0.28612911 0.34670051 ... 0.96770407 0.01867877 0.59377972]
 [1.         0.29672824 0.44269315 ... 0.93021014 0.04781113 0.58411008]
 [0.         0.68058293 0.90556958 ... 0.57031088 0.36479178 0.23758798]
 ...
 [1.         0.89897345 0.30129859 ... 0.99319135 0.00369213 0.79357682]
 [1.         0.90536988 0.24318971 ... 0.98480378 0.00825277 0.64339611]
 [0.         0.92032181 0.26909182 ... 0.97773157 0.01214462 0.59663306]]


gender      PPE     RPDE  meanPeriodPulses  stdDevPeriodPulses  \
0         1  0.28937  0.40286          0.003429            0.000089   
1         1  0.29855  0.47168          0.003445            0.000145   
2         0  0.63101  0.80353          0.006561            0.002738   
3         1  0.27100  0.66652          0.006317            0.000028   
4         0  0.83786  0.70689          0.006768            0.001837   
..      ...      ...      ...               ...                 ...   
751       1  0.85083  0.58982          0.008340            0.000060   
752       0  0.88389  0.46815          0.005069            0.000103   
753       1  0.82016  0.37031          0.007257            0.000049   
754       1  0.82570  0.32865          0.005610            0.000059   
755       0  0.83865  0.34722          0.005599            0.000053   

     locPctJitter  locAbsJitter  rapJitter  ppq5Jitter  ddpJitter  locShimmer  \
0         0.00131      0.000004    0.00013     0.00037    0.00040     0.04988   
1         0.00190      0.000007    0.00021     0.00056    0.00062     0.05372   
2         0.01505      0.000099    0.00442     0.00875    0.01327     0.13841   
3         0.00059      0.000004    0.00014     0.00032    0.00041     0.17188   
4         0.01119      0.000076    0.00341     0.00656    0.01022     0.18701   
..            ...           ...        ...         ...        ...         ...   
751       0.00176      0.000015    0.00057     0.00111    0.00171     0.09902   
752       0.00076      0.000004    0.00011     0.00030    0.00034     0.02978   
753       0.00086      0.000006    0.00020     0.00045    0.00059     0.02734   
754       0.00111      0.000006    0.00021     0.00052    0.00062     0.01803   
755       0.00082      0.000005    0.00016     0.00036    0.00047     0.04631   

     apq3Shimmer  apq5Shimmer  apq11Shimmer  ddaShimmer  \
0        0.02501      0.02894       0.04355     0.07503   
1        0.02610      0.03099       0.04773     0.07829   
2        0.06392      0.08508       0.11153     0.19176   
3        0.09051      0.12890       0.12624     0.27152   
4        0.10070      0.15668       0.26624     0.30209   
..           ...          ...           ...         ...   
751      0.05094      0.06497       0.07772     0.15282   
752      0.01597      0.01916       0.02271     0.04790   
753      0.01309      0.01662       0.02548     0.03926   
754      0.00950      0.01146       0.01501     0.02849   
755      0.02463      0.03177       0.03394     0.07389   

     meanAutoCorrHarmonicity  meanNoiseToHarmHarmonicity  \
0                   0.986148                    0.014834   
1                   0.970784                    0.037006   
2                   0.823307                    0.278253   
3                   0.793984                    0.277690   
4                   0.590345                    0.737512   
..                       ...                         ...   
751                 0.974846                    0.026313   
752                 0.995544                    0.004480   
753                 0.996592                    0.003428   
754                 0.993155                    0.006899   
755                 0.990257                    0.009861   

     meanHarmToNoiseHarmonicity  
0                        20.384  
1                        20.079  
2                         9.149  
3                         6.280  
4                         1.655  
..                          ...  
751                      17.651  
752                      24.005  
753                      26.686  
754                      21.949  
755                      20.474  

[756 rows x 18 columns]